language: cpp
compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - realpath
      - libstdc++-5-dev
      - libncursesw5-dev

install:
  - root=$PWD
  - mkdir bin
  - git clone git://github.com/mawww/kakoune repositories/github.com/mawww/kakoune
  - cd repositories/github.com/mawww/kakoune/src
  - make
  - ln --symbolic $PWD/kak $root/bin
  - cd $root

script:
  - export PATH="$PWD/bin:$PATH"
  - test/run
